name: GroundItemClear
version: 1.2
main: me.MFHKiwi.GroundItemClear.GroundItemClear
description: A plugin for CraftBukkit 1060 that automatically clears ground items to reduce lag.
author: MFHKiwi
commands:
   gic:
      description: Interact with GroundItemClear
      usage: /gic <argument>
      aliases: [grounditemclear, grounditem, itemclear]
permissions:
   gic.clear:
      description: Gives access to use /gic clear
      default: op